#!/bin/sh
chmod +x  /etc/init.d/nft-limiter /usr/bin/nft-limiter
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@nft-limiter[-1]
	add ucitrack nft-limiter
	set ucitrack.@nft-limiter[-1].init=nft-limiter
	commit ucitrack
EOF

[ -s /etc/config/nft-limiter ] || echo "config nft-limiter" > /etc/config/nft-limiter

rm -f /tmp/luci-indexcache
exit 0
