#!/bin/sh /etc/rc.common
#
# nft-limiter init script - nftables/fw4 edition
#

START=99
USE_PROCD=1

NAME=nftlimiter

start_service() {
    nft-limiter stop

    local enabled
    enabled=$(uci -q get "${NAME}.@${NAME}[0].enabled")
    [ "$enabled" = "1" ] || return 0

    nft-limiter start
}

service_triggers() {
    procd_add_reload_trigger 'nftlimiter'
}

stop_service() {
    nft-limiter stop
}
